### ISSUE TITLE
Feature 1: User can see their car

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a simple HTML skeleton that includes car.
- [x] Pick a background color
- [x] Have the car in a start position
- [x] Make sure entire screen is available
