### ISSUE TITLE
Feature 2: User can turn their car

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add four separate classes to the CSS file to change which direction the car is facing. Test to see if it works.
- [x] Make car rotate down on keydown down arrow key.
- [x] Make car rotate left on keydown left arrow key.
- [x] Make car rotate up on keydown up arrow key.
- [x] Make car rotate right on keydown right arrow key.
- [x] Have the transition between rotations be smooth.
