### ISSUE TITLE
Feature 5: User can steer their car

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add conditional statements and use the style property of elements objects to:

> - [x] If car is facing south, car's top boxset styles should be added to 
> - [x] If car is facing north, car's top boxset styles should be subtracted to 
> - [x] If car is facing west, car's left boxset styles should be added to 
> - [x] If car is facing east, car's left boxset styles should be subtracted to
- [x] Remove any CSS styles that are not used
- [x] Check for bugs
